# Generated by Django 3.2.8 on 2021-12-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20211109_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
