# Generated by Django 3.2.8 on 2021-12-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_funcionario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['data_nascimento']},
        ),
    ]
